config/routes.rb
Test2::Application.routes.draw do

  resources :sensors

  devise_for :users

  resources :gateways

  root :to => "gateways#index"
  match "/users/sign_out", to: "devise/sessions#destroy", :as => "logout"
  match '/sensors/today/:id' => 'sensors#today'

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  attr_accessible :sensor_id, :name, :sensor_type, :gateway_id
  belongs_to :gateway
  has_many :sensor_reading
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_filter :authenticate_user!
  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sensors }
    end
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
    @sensor = Sensor.find(params[:id])
    #------------------------------------------------------------
    #@sensor.sensor_reading can't return the readings because the 
    #sensors ID is compared with sensorReading sesor_id column
    #------------------------------------------------------------
    @sensor_data = SensorReading.where("sensor_id = ? AND gateway_id = ?", @sensor.sensor_id, @sensor.gateway_id)

    respond_to do |format|
      format.html # show.html.erb
      
      format.json { render json: @sensor_data }
      format.json { render json: @sensor }   
    end
  end

  # GET /sensors/new
  # GET /sensors/new.json
  def new
    @sensor = Sensor.new

    #------------------------------------------------------------------------
    # EDIT:
    #   Receives the id of the gateway and passes it to 'Sensor/View/new.html' 
    #------------------------------------------------------------------------

    @gateway_id = params[:gateway_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sensor }
      format.json { render json: @gateway_id }
    end
  end

  # GET /sensors/1/edit
  def edit
    @sensor = Sensor.find(params[:id])
    @gateway_id = @sensor.gateway_id
    respond_to do |format|
      format.html
      format.json { render json:  @gateway_id}
    end
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(params[:sensor])

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to @sensor, notice: 'Sensor was successfully created.' }
        format.json { render json: @sensor, status: :created, location: @sensor }
      else
        format.html { render action: "new" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sensors/1
  # PUT /sensors/1.json
  def update
    @sensor = Sensor.find(params[:id])

    respond_to do |format|
      if @sensor.update_attributes(params[:sensor])
        format.html { redirect_to @sensor, notice: 'Sensor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor = Sensor.find(params[:id])
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to gateway_path }
      format.json { head :no_content }
    end
  end
  def today
    @sensor = Sensor.find(params[:id])
    @sensor_data = SensorReading.where("sensor_id = ? AND gateway_id = ? AND created_at >= ?", @sensor.sensor_id, @sensor.gateway_id, Time.now.beginning_of_day)

    respond_to do |format|  
      format.json { render json: @sensor_data }
    end
  end
end

app/helpers/sensors_helper.rb
module SensorsHelper
	
	def getMin(sensor_data)
		@no_value = "No value"

		if sensor_data[0] != nil	
			@min = sensor_data[0].value.to_i

			sensor_data.each do |sensor_data| 
				if sensor_data.value.to_i < @min 
					@min = sensor_data.value.to_i
				end
			end
			return @min.to_s
		else
			return @no_value
		end
	end

	def getMax(sensor_data)
		#@no_value is not needed, it is already defined in the getMin method
		@no_value = "No value"
		if sensor_data[0] != nil
			@max = sensor_data[0].value.to_i

			sensor_data.each do |sensor_data| 
				if sensor_data.value.to_i > @max 
					@max = sensor_data.value.to_i
				end
			end
			return @max.to_s
		else
			return @no_value
		end

	end

	def getCurrent(sensor_data)
		if sensor_data[0] != nil
			return sensor_data.last.value
		else
			return @no_value
		end
		
	end

	def getAverage(sensor_data)
		if sensor_data[0] != nil
			@value = 0
			sensor_data.each do |sensor_data|
				@value += sensor_data.value.to_i
			end
			@average = @value/@sensor_data.length
			return @average
		else
			return @no_value
		end
	end

end

app/views/sensors/_form.html.erb
<%= form_for(@sensor) do |f| %>
 <% if @sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% @sensor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sensor_type %><br />
    <%= f.text_field :sensor_type %>
  </div>
  <div class="field">
    <%= f.label :sensor_id %><br />
    <%= f.text_field :sensor_id %>
  </div>
    <!-- Passes a hidden_field with the gateways value, @gw comes from 'Controller: sensor/new' -->
    <%= f.hidden_field :gateway_id, { :value => @gateway_id } %>
    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<h1>Editing sensor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sensor %> |
<%= link_to 'Back', sensor_path(@sensor) %>

app/views/sensors/index.html.erb
<h1>Listing sensors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Sensor type</th>
    <th>Sensor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sensors.each do |sensor| %>
  <tr>
    <td><%= sensor.name %></td>
    <td><%= sensor.sensor_type %></td>
    <td><%= sensor.sensor_id %></td>
    <td><%= link_to 'Show', sensor %></td>
    <td><%= link_to 'Edit', edit_sensor_path(sensor) %></td>
    <td><%= link_to 'Destroy', sensor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sensor', new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New sensor for gateway: <%= @gateway_id %></h1>

<%= render 'form' %>

<%= link_to 'Back', gateway_path(@gateway_id) %>

app/views/sensors/show.html.erb
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<script type='text/javascript'>
      google.load('visualization', '1', {packages:['gauge']});
      // params that will be used in the external .js scripts!

      var sensor_url_id = <%= @sensor.id %>;
      var sensor_type = '<%= @sensor.sensor_type %>';
      var sensor_id = '<%= @sensor.sensor_id %>'
      var min_value = <%= getMin(@sensor_data) %>;
      var max_value = <%= getMax(@sensor_data) %>;
      var sensor_unit;

      if (sensor_type == 'Temperature') {
        sensor_unit = '°C';
      }
      else if(sensor_type == 'Weight'){
        sensor_unit = 'kg';
      };

</script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sensor.name %>
<br />
  <b>Sensor type:</b>
  <%= @sensor.sensor_type %>
</p>
<% if(@sensor_data[0] != nil) %>
  <p id="max_gauge_div" style="width: 150px; height: 150px; float: left;"></p>
  <p id="min_gauge_div" style="width: 150px; height: 150px; float: left;"></p>
  <p id="current_gauge_div" style="width: 150px; height: 150px; float: left;"></p>
<% end %>

<div id="highchart" style="min-width: 400px; height: 400px; margin: 0 auto; clear:left;"></div>
<button id='today' type="button">Readings from today</button>
<button id='all' type="button">All readings</button>

<%#<p id="line_chart_div" style="width: 450px; height: 250px; "></p> %>
<p>
<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Destroy', @sensor, confirm: 'Are you sure?', method: :delete %> |
<%= link_to 'Back', gateway_path(@sensor.gateway_id) %>
</p>