config/routes.rb
Test2::Application.routes.draw do

  resources :sensors

  devise_for :users

  resources :gateways

  root :to => "gateways#index"
  match "/users/sign_out", to: "devise/sessions#destroy", :as => "logout"
  match '/sensors/today/:id' => 'sensors#today'

end

app/models/gateway.rb
class Gateway < ActiveRecord::Base
  attr_accessible :gateway_id, :name, :use
  belongs_to :user
  has_many :sensor

end

app/controllers/gateways_controller.rb
class GatewaysController < ApplicationController
  before_filter :authenticate_user!
  # GET /gateways
  # GET /gateways.json
  def index

    #------------------------------------------------------------------------
    # EDIT:
    #   Gets all gateways that belongs to the current user. 
    #------------------------------------------------------------------------

    #@gateways = Gateway.all
    @gateways = Gateway.where({ :owner => [current_user]}).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gateways }
    end
  end

  # GET /gateways/1
  # GET /gateways/1.json
  def show

    #------------------------------------------------------------------------
    # EDIT: 
    #   Gets the gateway with gateway/'ID' if the user owns that gateway else 
    # redirect to 'index' page. 
    #   Gets sensors that belongs to this Gateway.
    #------------------------------------------------------------------------

    @gateway = Gateway.find_by_id_and_owner(params[:id], current_user.id)

    if @gateway.nil?
      redirect_to :action=>'index'
    else  
       @sensor = @gateway.sensor  
      respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gateway}
      format.json { render json: @sensor}
      end
    end
  end

  # GET /gateways/new
  # GET /gateways/new.json
  def new
    @gateway = Gateway.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gateway.id }
    end
  end

  # GET /gateways/1/edit
  def edit

    #------------------------------------------------------------------------
    # EDIT: 
    #   Gets the gateway with gateway/'ID' if the user owns that gateway else 
    # redirect to 'index' page 
    #------------------------------------------------------------------------

    #@gateway = Gateway.find(params[:id])
    @gateway = Gateway.find_by_id_and_owner(params[:id], current_user.id)

    if @gateway.nil?
      redirect_to :action=>'index'
    else
    end
  end

  # POST /gateways
  # POST /gateways.json
  def create
    @gateway = Gateway.new(params[:gateway])

    @gateway.owner = current_user.id

    respond_to do |format|
      if @gateway.save

        format.html { redirect_to @gateway, notice: 'Gateway was successfully created.' }
        format.json { render json: @gateway, status: :created, location: @gateway }
      else
        format.html { render action: "new" }
        format.json { render json: @gateway.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /gateways/1
  # PUT /gateways/1.json
  def update
    @gateway = Gateway.find(params[:id])

    respond_to do |format|
      if @gateway.update_attributes(params[:gateway])
        format.html { redirect_to @gateway, notice: 'Gateway was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gateway.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gateways/1
  # DELETE /gateways/1.json
  def destroy
    @gateway = Gateway.find(params[:id])
    @gateway.destroy

    respond_to do |format|
      format.html { redirect_to gateways_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/gateways_helper.rb
module GatewaysHelper
end

app/views/gateways/_form.html.erb
<%= form_for(@gateway) do |f| %>
  <% if @gateway.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gateway.errors.count, "error") %> prohibited this gateway from being saved:</h2>

      <ul>
      <% @gateway.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gateway_id %><br />
    <%= f.text_field :gateway_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gateways/edit.html.erb
<h1>Editing gateway</h1>

<%= render 'form' %>

<%= link_to 'Show', @gateway %> |
<%= link_to 'Back', gateways_path %>

app/views/gateways/index.html.erb
<h1>Listing gateways</h1>

<% if @gateways.length != 0 %>
  <table>
   <tr>
     <th>Name</th>
     <th>Gateway</th>
     <th></th>
     <th></th>
     <th></th>
    </tr>

  <% @gateways.each do |gateway| %>
    <tr>
      <td><%= gateway.name %></td>
      <td><%= gateway.gateway_id %></td>
      <td><%= link_to 'Show', gateway %></td>
      <td><%= link_to 'Edit', edit_gateway_path(gateway) %></td>
      <td><%= link_to 'Destroy', gateway, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>

  <br />
  <%= link_to 'New Gateway', new_gateway_path %>

<% else %>
<p> Found no gateways, add a <%= link_to 'new Gateway', new_gateway_path %></p>
<% end %>

app/views/gateways/new.html.erb
<h1>New gateway</h1>

<%= render 'form' %>

<%= link_to 'Back', gateways_path %>

app/views/gateways/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gateway.name %>
</p>

<p>
  <b>Gateway:</b>
  <%= @gateway.gateway_id %>
</p>
<div>
	<p> 
		<b>Sensors:</b>
		<% if @sensor.length != 0 %>
			<% @sensor.each do |sensor| %>
			<br />
			<%= sensor.name %>
			-
			<%= sensor.sensor_type %>
			-
			<%= link_to 'Show', sensor %>
			<% end %>
		<% else %>
		<b> Found no sensors, add a <%= link_to 'new Sensor',new_sensor_path(:actions => 'new', :gateway_id => @gateway)%></br>
		<% end %>	
	</p>
</div>


<%= link_to 'Edit', edit_gateway_path(@gateway) %> |
<%= link_to 'Back', gateways_path %> |
<%= link_to 'New Sensor',new_sensor_path(:actions => 'new', :gateway_id => @gateway)%> |